# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tb_payment?TimeZone=Europe/Kyiv
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Kyiv

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#EXECUTORS
executor.db.core_pool_size=10
executor.db.max_pool_size=20
executor.db.queue_capacity=100

#WORKSPACE
workspace.sync.rate_millis=3600000
workspace.sync.usage_snapshot=60000

#LOGGER
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.root= INFO
logging.level.org.mirgor= DEBUG
logging.level.org.hibernate.SQL= DEBUG
logging.level.org.hibernate.orm.jdbc.bind= INFO